In [157]:
import pandas as pd
import numpy as np
# import datetime
from datetime import datetime, timezone
import requests
import json
import matplotlib.pyplot as plt
import math
import scipy.stats as st

In [158]:
def create_tuple(response):
    # all data
    response_data = response.json()
    # print(response_data)
    # data for a single target
    response_datum = response_data[0]
    # print(response_datum)
    # the target - e.g. "120MapleAve.STM.M22-V/AverageMassFlow"
    response_target = response_datum['target']
    # the metric for this target - e.g. "Steam"
    #response_metric = response_datum['metric']
    # print(response_metric)
    # the datapoints as a list of lists
    response_datapoints = response_datum['datapoints']
    # print(response_datapoints)
    # array of tuples for numpy
    tuple_array = [tuple(x) for x in response_datapoints]
    # make a numpy array
    npa = np.array(tuple_array, dtype=[
                   ('value', np.double), ('ts', 'datetime64[ms]')])
    # npa = npa.astype([('value', np.double), ('ts', datetime)])

    # print("here")
    # for index, i in enumerate(npa):
    #   j = pd.to_datetime(i[1]).replace(tzinfo=timezone.utc).astimezone(tz="America/New_York")
    #   npa[index][1] = j
    return npa

In [159]:
def current_date():
    return str(datetime.now())

In [160]:
"""
Returns an array of tuples where tuple[0] is the metric, and tuple[1] is the time 
of measurement

Target: a WebCTRL point name in the form of a string 
Example: "#biotech/biotech_4th_floor/fourth_floor_fume_hood_lab_spaces/lab_433_control/zone/zone_temp/trend_log"

Server: a string representing the WebCTRL server our point exists in
Example: "biotech_main"

Start: the start time we wish to be querying data about (in string format)
Example: "2021-12-31T11:00Z"

End: The end time we wish to be querying data about
Example: "2022-12-31T11:00Z"
"""
def fume_query(target,server, start,end):
  url = "https://ypsu0n34jc.execute-api.us-east-1.amazonaws.com/dev/query"
  data = {
      "range": {
        "from": start,
        "to": end,
      },
      "targets": [
        {
          "payload": {
            "schema": server,
          },
          "target": target
        }
      ],

    }
  request = requests.post(url, json=data)
  print(request)
  # print(request.json())
  return create_tuple(request)

In [161]:
"""
Returns a time series of the ithaca air temperature over the respective 
"""

def outside_temp(start,end):
  # https://ypsu0n34jc.execute-api.us-east-1.amazonaws.com/dev/query doesn't work
  # https://portal.emcs.cornell.edu/api/datasources/proxy/5/query works
  # https://portal-api.emcs.cucloud.net/query works
  url = "https://portal-api.emcs.cucloud.net/query"
  target = "GameFarmRoadWeatherStation.TAVG_H_F"
  data = {
    "range": {
        "from": start,
        "to": end
    },
    "targets": [
        {
            "target": target,
        }
    ]
  }
  request = requests.post(url, json=data)
  print(request)
#   print(request.json())
  return create_tuple(request)

In [162]:
from datetime import datetime
from dateutil import parser
import matplotlib.dates as mdates

def query(target_list, server, start, end):
  cfm_master = fume_query(target_list[0],server,start,end)
  sash_master = fume_query(target_list[3],server,start,end)
  occ_master = fume_query(target_list[2],server,start,end)
  internal_temp_master = fume_query(target_list[1],server,start,end)
  external_temp_master = outside_temp(start,end)
  print("\nExternal Temp Master ", external_temp_master)

  cfm_list = pd.Series(data=[i[0] for i in cfm_master], index=[i[1] for i in cfm_master])
  print("CFM List: ", cfm_list)
  cfm_list = cfm_list[~cfm_list.index.duplicated()]
  print("CFM List new: ", cfm_list)

  sash_list = pd.Series(data=[i[0] for i in sash_master], index=[i[1] for i in sash_master])
  print("\nSash List: ", sash_list)
  sash_list = sash_list[~sash_list.index.duplicated()]
  print("\nSash List new: ", sash_list)

  occ_list = pd.Series(data=[i[0] for i in occ_master], index=[i[1] for i in occ_master])
  print("\nOCC List: ", occ_list)
  occ_list = occ_list[~occ_list.index.duplicated()]
  print("\nOCC List new: ", occ_list)
  
  internal_temp_list = pd.Series(data=[i[0] for i in internal_temp_master], index=[i[1] for i in internal_temp_master])
  print("\nInternal Temp List: ", internal_temp_list)
  internal_temp_list = internal_temp_list[~internal_temp_list.index.duplicated()]
  print("\nInternal Temp List new: ", internal_temp_list)

  external_temp_list = pd.Series(data=[i[0] for i in external_temp_master], index=[i[1] for i in external_temp_master])
  print("\nExternal Temp List: ", external_temp_list)
  # external_temp_list = pd.read_csv("C:/Users/Dan/Documents/GitHub/fume-hood-dashboard/game_farm/hist.csv", index_col=0).squeeze()
  external_temp_list.index = external_temp_list.index.astype('datetime64[ns]')
  print("\nExternal Temp List: ", external_temp_list)

  # hourly data frame
  df = pd.concat([cfm_list, sash_list, occ_list, internal_temp_list, external_temp_list], axis=1)
  df.columns = ["cfm", "sash" ,"occ", "internal temp", "external temp"]
  display(df)

  df["BTUh"] = 1.08 * df["cfm"] * (df["internal temp"] - df["external temp"])

  display(df)

In [163]:
def new_query(target_list, server, start, end):
  external_temp_master = outside_temp(start,end)
  print("\nExternal Temp Master ", external_temp_master)
  cfm_master = fume_query(target_list[0],server,start,end)
  sash_master = fume_query(target_list[3],server,start,end)
  occ_master = fume_query(target_list[2],server,start,end)
  internal_temp_master = fume_query(target_list[1],server,start,end)
  
  cfm_list = pd.Series(data=[i[0] for i in cfm_master], index=[i[1] for i in cfm_master])
  print("CFM List: ", cfm_list)
  cfm_list = cfm_list[~cfm_list.index.duplicated()]
  print("CFM List new: ", cfm_list)

  sash_list = pd.Series(data=[i[0] for i in sash_master], index=[i[1] for i in sash_master])
  print("\nSash List: ", sash_list)
  sash_list = sash_list[~sash_list.index.duplicated()]
  print("\nSash List new: ", sash_list)

  occ_list = pd.Series(data=[i[0] for i in occ_master], index=[i[1] for i in occ_master])
  print("\nOCC List: ", occ_list)
  occ_list = occ_list[~occ_list.index.duplicated()]
  print("\nOCC List new: ", occ_list)
  
  internal_temp_list = pd.Series(data=[i[0] for i in internal_temp_master], index=[i[1] for i in internal_temp_master])
  print("\nInternal Temp List: ", internal_temp_list)
  internal_temp_list = internal_temp_list[~internal_temp_list.index.duplicated()]
  print("\nInternal Temp List new: ", internal_temp_list)

  external_temp_list = pd.Series(data=[i[0] for i in external_temp_master], index=[i[1] for i in external_temp_master])
  print("\nExternal Temp List: ", external_temp_list)
  # external_temp_list = pd.read_csv("C:/Users/Dan/Documents/GitHub/fume-hood-dashboard/game_farm/hist.csv", index_col=0).squeeze()
  external_temp_list.index = external_temp_list.index.astype('datetime64[ns]')
  print("\nExternal Temp List: ", external_temp_list)

  # interpolating External Temperature values
  ext_temp_hr = external_temp_list.tolist()
  ext_temp = []
  i = 0
  while i < (len(ext_temp_hr)-1):
    initial = ext_temp_hr[i]
    difference = (ext_temp_hr[i+1] - initial)/12
    ext_temp_5 = []
    for x in range(12):
      ext_temp_5.append(initial + difference*x)
    print("\n 12 Ext Temp Values: ", ext_temp_5)
    ext_temp = ext_temp + ext_temp_5
    i += 1
  ext_temp = ext_temp[12:] + [ext_temp_hr[-1]]
  print("\nList of New Ext Temp Values: ", ext_temp)

  # Internal Temperatures span multiple days, External Temperatures span one day
  new_external_temp_list = pd.Series(data=ext_temp, index=[i[1] for i in internal_temp_master[:277]])
  print("\nNew External Temp List: ", new_external_temp_list)

  new_df = pd.concat([cfm_list, sash_list, occ_list, internal_temp_list, new_external_temp_list], axis=1)
  new_df.columns = ["cfm", "sash" ,"occ", "internal temp", "external temp"]
  display(new_df)
  new_df = new_df.dropna()
  new_df["BTUh"] = 1.08 * new_df["cfm"] * (new_df["internal temp"] - new_df["external temp"])

  display(new_df)

In [164]:
target_list = ["#biotech/biotech_4th_floor/fourth_floor_fume_hood_lab_spaces/lab_433_control/hoodvalve_flow/trend_log",
               "#biotech/biotech_4th_floor/fourth_floor_fume_hood_lab_spaces/lab_433_control/zone/zone_temp/trend_log",
               "#biotech/biotech_4th_floor/fourth_floor_fume_hood_lab_spaces/lab_433_control/occ_trend",
               "#biotech/biotech_4th_floor/fourth_floor_fume_hood_lab_spaces/lab_433_control/hood_sash"]
server = "biotech_main"
start = str(datetime(2022, 11, 17))
end = str(datetime(2022, 11, 18))

#query(target_list,server,start,end)
new_query(target_list,server,start,end)

<Response [200]>

External Temp Master  [(37.6286, '2022-11-17T00:00:00.000') (37.1696, '2022-11-17T01:00:00.000')
 (36.59  , '2022-11-17T02:00:00.000') (36.203 , '2022-11-17T03:00:00.000')
 (36.1958, '2022-11-17T04:00:00.000') (35.9762, '2022-11-17T05:00:00.000')
 (35.384 , '2022-11-17T06:00:00.000') (34.8314, '2022-11-17T07:00:00.000')
 (34.5938, '2022-11-17T08:00:00.000') (34.2158, '2022-11-17T09:00:00.000')
 (33.4256, '2022-11-17T10:00:00.000') (32.3528, '2022-11-17T11:00:00.000')
 (32.45  , '2022-11-17T12:00:00.000') (33.1556, '2022-11-17T13:00:00.000')
 (34.4642, '2022-11-17T14:00:00.000') (34.862 , '2022-11-17T15:00:00.000')
 (32.0828, '2022-11-17T16:00:00.000') (31.8758, '2022-11-17T17:00:00.000')
 (34.0178, '2022-11-17T18:00:00.000') (31.9406, '2022-11-17T19:00:00.000')
 (33.9044, '2022-11-17T20:00:00.000') (34.1906, '2022-11-17T21:00:00.000')
 (33.0026, '2022-11-17T22:00:00.000') (32.8064, '2022-11-17T23:00:00.000')
 (32.4374, '2022-11-18T00:00:00.000')]
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
CFM List:  2022-11-17 05:00:00    224.13
2022-11-17 05:05:00    224.13
2022-11-17 05:10:00    224.13
2022-11-17 05:15:00    225.10
2022-11-17 05:20:00    225.10
                        ...
2022-11-19 04:35:00    224.13
2022-11-19 04:40:00    225.59
2022-11-19 04:45:00    227.06
2022-11-19 04:50:00    227.06
2022-11-19 04:55:00    221.20
Length: 576, dtype: float64
CFM List new:  2022-11-17 05:00:00    224.13
2022-11-17 05:05:00    224.13
2022-11-17 05:10:00    224.13
2022-11-17 05:15:00    225.10
2022-11-17 05:20:00    225.10
                        ...
2022-11-19 04:35:00    224.13
2022-11-19 04:40:00    225.59
2022-11-19 04:45:00    227.06
2022-11-19 04:50:00    227.06
2022-11-19 04:55:00    221.20
Length: 576, dtype: float64

Sash List:  2022-11-17 05:00:00    1.2
2022-11-17 05:05:00    1.2
2022-11-17 05:10:00    1.2
2022-11-17 05:15:00    1.2
2022-11-17 05:20:00    1.2
                      ...
2022-11-19 04:35:00    1.2
2022-11-19 04:40:00    1.2
2022-11-19 04:45:00    1.2
2022-11-19 04:50:00    1.2
2022-11-19 04:55:00    1.2
Length: 576, dtype: float64

Sash List new:  2022-11-17 05:00:00    1.2
2022-11-17 05:05:00    1.2
2022-11-17 05:10:00    1.2
2022-11-17 05:15:00    1.2
2022-11-17 05:20:00    1.2
                      ...
2022-11-19 04:35:00    1.2
2022-11-19 04:40:00    1.2
2022-11-19 04:45:00    1.2
2022-11-19 04:50:00    1.2
2022-11-19 04:55:00    1.2
Length: 576, dtype: float64

OCC List:  2022-11-17 05:00:00    1.0
2022-11-17 05:05:00    1.0
2022-11-17 05:10:00    1.0
2022-11-17 05:15:00    1.0
2022-11-17 05:20:00    1.0
                      ...
2022-11-19 04:35:00    0.0
2022-11-19 04:40:00    0.0
2022-11-19 04:45:00    0.0
2022-11-19 04:50:00    0.0
2022-11-19 04:55:00    0.0
Length: 576, dtype: float64

OCC List new:  2022-11-17 05:00:00    1.0
2022-11-17 05:05:00    1.0
2022-11-17 05:10:00    1.0
2022-11-17 05:15:00    1.0
2022-11-17 05:20:00    1.0
                      ...
2022-11-19 04:35:00    0.0
2022-11-19 04:40:00    0.0
2022-11-19 04:45:00    0.0
2022-11-19 04:50:00    0.0
2022-11-19 04:55:00    0.0
Length: 576, dtype: float64

Internal Temp List:  2022-11-17 05:00:00    72.2
2022-11-17 05:05:00    72.4
2022-11-17 05:10:00    72.4
2022-11-17 05:15:00    72.1
2022-11-17 05:20:00    71.8
                       ...
2022-11-19 04:35:00    70.3
2022-11-19 04:40:00    70.3
2022-11-19 04:45:00    70.2
2022-11-19 04:50:00    70.2
2022-11-19 04:55:00    70.2
Length: 576, dtype: float64

Internal Temp List new:  2022-11-17 05:00:00    72.2
2022-11-17 05:05:00    72.4
2022-11-17 05:10:00    72.4
2022-11-17 05:15:00    72.1
2022-11-17 05:20:00    71.8
                       ...
2022-11-19 04:35:00    70.3
2022-11-19 04:40:00    70.3
2022-11-19 04:45:00    70.2
2022-11-19 04:50:00    70.2
2022-11-19 04:55:00    70.2
Length: 576, dtype: float64

External Temp List:  2022-11-17 00:00:00    37.6286
2022-11-17 01:00:00    37.1696
2022-11-17 02:00:00    36.5900
2022-11-17 03:00:00    36.2030
2022-11-17 04:00:00    36.1958
2022-11-17 05:00:00    35.9762
2022-11-17 06:00:00    35.3840
2022-11-17 07:00:00    34.8314
2022-11-17 08:00:00    34.5938
2022-11-17 09:00:00    34.2158
2022-11-17 10:00:00    33.4256
2022-11-17 11:00:00    32.3528
2022-11-17 12:00:00    32.4500
2022-11-17 13:00:00    33.1556
2022-11-17 14:00:00    34.4642
2022-11-17 15:00:00    34.8620
2022-11-17 16:00:00    32.0828
2022-11-17 17:00:00    31.8758
2022-11-17 18:00:00    34.0178
2022-11-17 19:00:00    31.9406
2022-11-17 20:00:00    33.9044
2022-11-17 21:00:00    34.1906
2022-11-17 22:00:00    33.0026
2022-11-17 23:00:00    32.8064
2022-11-18 00:00:00    32.4374
dtype: float64

External Temp List:  2022-11-17 00:00:00    37.6286
2022-11-17 01:00:00    37.1696
2022-11-17 02:00:00    36.5900
2022-11-17 03:00:00    36.2030
2022-11-17 04:00:00    36.1958
2022-11-17 05:00:00    35.9762
2022-11-17 06:00:00    35.3840
2022-11-17 07:00:00    34.8314
2022-11-17 08:00:00    34.5938
2022-11-17 09:00:00    34.2158
2022-11-17 10:00:00    33.4256
2022-11-17 11:00:00    32.3528
2022-11-17 12:00:00    32.4500
2022-11-17 13:00:00    33.1556
2022-11-17 14:00:00    34.4642
2022-11-17 15:00:00    34.8620
2022-11-17 16:00:00    32.0828
2022-11-17 17:00:00    31.8758
2022-11-17 18:00:00    34.0178
2022-11-17 19:00:00    31.9406
2022-11-17 20:00:00    33.9044
2022-11-17 21:00:00    34.1906
2022-11-17 22:00:00    33.0026
2022-11-17 23:00:00    32.8064
2022-11-18 00:00:00    32.4374
dtype: float64

 12 Ext Temp Values:  [37.6286, 37.59035, 37.552099999999996, 37.51385, 37.4756, 37.43735, 37.399100000000004, 37.36085, 37.3226, 37.28435, 37.2461, 37.20785]

 12 Ext Temp Values:  [37.1696, 37.121300000000005, 37.073, 37.0247, 36.976400000000005, 36.9281, 36.8798, 36.831500000000005, 36.7832, 36.7349, 36.686600000000006, 36.6383]

 12 Ext Temp Values:  [36.59, 36.557750000000006, 36.5255, 36.49325, 36.461000000000006, 36.42875, 36.3965, 36.364250000000006, 36.332, 36.29975, 36.267500000000005, 36.23525]

 12 Ext Temp Values:  [36.203, 36.202400000000004, 36.201800000000006, 36.2012, 36.2006, 36.2, 36.1994, 36.1988, 36.1982, 36.1976, 36.197, 36.1964]

 12 Ext Temp Values:  [36.1958, 36.177499999999995, 36.1592, 36.1409, 36.1226, 36.104299999999995, 36.086, 36.0677, 36.0494, 36.031099999999995, 36.0128, 35.9945]

 12 Ext Temp Values:  [35.9762, 35.92685, 35.8775, 35.82815, 35.7788, 35.72945, 35.680099999999996, 35.63075, 35.5814, 35.53205, 35.4827, 35.43335]

 12 Ext Temp Values:  [35.384, 35.33795, 35.2919, 35.245850000000004, 35.1998, 35.15375, 35.1077, 35.06165, 35.0156, 34.96955, 34.923500000000004, 34.87745]

 12 Ext Temp Values:  [34.8314, 34.8116, 34.7918, 34.772000000000006, 34.7522, 34.7324, 34.7126, 34.692800000000005, 34.673, 34.6532, 34.6334, 34.613600000000005]

 12 Ext Temp Values:  [34.5938, 34.5623, 34.5308, 34.499300000000005, 34.467800000000004, 34.4363, 34.4048, 34.3733, 34.3418, 34.3103, 34.278800000000004, 34.2473]

 12 Ext Temp Values:  [34.2158, 34.149950000000004, 34.0841, 34.01825, 33.952400000000004, 33.88655, 33.8207, 33.754850000000005, 33.689, 33.62315, 33.557300000000005, 33.49145]

 12 Ext Temp Values:  [33.4256, 33.336200000000005, 33.2468, 33.1574, 33.068000000000005, 32.9786, 32.8892, 32.799800000000005, 32.7104, 32.621, 32.531600000000005, 32.4422]

 12 Ext Temp Values:  [32.3528, 32.3609, 32.369, 32.3771, 32.385200000000005, 32.3933, 32.4014, 32.4095, 32.4176, 32.425700000000006, 32.433800000000005, 32.441900000000004]

 12 Ext Temp Values:  [32.45, 32.5088, 32.5676, 32.626400000000004, 32.6852, 32.744, 32.802800000000005, 32.8616, 32.9204, 32.9792, 33.038, 33.0968]

 12 Ext Temp Values:  [33.1556, 33.26465, 33.3737, 33.482749999999996, 33.5918, 33.70085, 33.8099, 33.918949999999995, 34.028, 34.13705, 34.2461, 34.355149999999995]

 12 Ext Temp Values:  [34.4642, 34.49735, 34.530499999999996, 34.563649999999996, 34.5968, 34.62995, 34.6631, 34.69625, 34.7294, 34.762550000000005, 34.795700000000004, 34.82885]

 12 Ext Temp Values:  [34.862, 34.6304, 34.3988, 34.1672, 33.9356, 33.704, 33.4724, 33.2408, 33.0092, 32.7776, 32.546, 32.3144]

 12 Ext Temp Values:  [32.0828, 32.06555, 32.0483, 32.03105, 32.0138, 31.99655, 31.979300000000002, 31.96205, 31.9448, 31.92755, 31.9103, 31.893050000000002]

 12 Ext Temp Values:  [31.8758, 32.054300000000005, 32.232800000000005, 32.411300000000004, 32.589800000000004, 32.7683, 32.9468, 33.1253, 33.3038, 33.4823, 33.6608, 33.8393]

 12 Ext Temp Values:  [34.0178, 33.8447, 33.6716, 33.4985, 33.3254, 33.152300000000004, 32.9792, 32.8061, 32.633, 32.4599, 32.2868, 32.1137]

 12 Ext Temp Values:  [31.9406, 32.10425, 32.2679, 32.43155, 32.5952, 32.75885, 32.9225, 33.08615, 33.2498, 33.413450000000005, 33.5771, 33.740750000000006]

 12 Ext Temp Values:  [33.9044, 33.928250000000006, 33.9521, 33.975950000000005, 33.9998, 34.02365, 34.0475, 34.07135, 34.095200000000006, 34.11905, 34.142900000000004, 34.16675]

 12 Ext Temp Values:  [34.1906, 34.0916, 33.9926, 33.893600000000006, 33.7946, 33.6956, 33.5966, 33.497600000000006, 33.3986, 33.2996, 33.2006, 33.101600000000005]

 12 Ext Temp Values:  [33.0026, 32.98625, 32.9699, 32.95355, 32.9372, 32.92085, 32.9045, 32.888149999999996, 32.8718, 32.85545, 32.839099999999995, 32.82275]

 12 Ext Temp Values:  [32.8064, 32.77565, 32.744899999999994, 32.71415, 32.6834, 32.652649999999994, 32.6219, 32.59115, 32.560399999999994, 32.52965, 32.4989, 32.468149999999994]

List of New Ext Temp Values:  [37.1696, 37.121300000000005, 37.073, 37.0247, 36.976400000000005, 36.9281, 36.8798, 36.831500000000005, 36.7832, 36.7349, 36.686600000000006, 36.6383, 36.59, 36.557750000000006, 36.5255, 36.49325, 36.461000000000006, 36.42875, 36.3965, 36.364250000000006, 36.332, 36.29975, 36.267500000000005, 36.23525, 36.203, 36.202400000000004, 36.201800000000006, 36.2012, 36.2006, 36.2, 36.1994, 36.1988, 36.1982, 36.1976, 36.197, 36.1964, 36.1958, 36.177499999999995, 36.1592, 36.1409, 36.1226, 36.104299999999995, 36.086, 36.0677, 36.0494, 36.031099999999995, 36.0128, 35.9945, 35.9762, 35.92685, 35.8775, 35.82815, 35.7788, 35.72945, 35.680099999999996, 35.63075, 35.5814, 35.53205, 35.4827, 35.43335, 35.384, 35.33795, 35.2919, 35.245850000000004, 35.1998, 35.15375, 35.1077, 35.06165, 35.0156, 34.96955, 34.923500000000004, 34.87745, 34.8314, 34.8116, 34.7918, 34.772000000000006, 34.7522, 34.7324, 34.7126, 34.692800000000005, 34.673, 34.6532, 34.6334, 34.613600000000005, 34.5938, 34.5623, 34.5308, 34.499300000000005, 34.467800000000004, 34.4363, 34.4048, 34.3733, 34.3418, 34.3103, 34.278800000000004, 34.2473, 34.2158, 34.149950000000004, 34.0841, 34.01825, 33.952400000000004, 33.88655, 33.8207, 33.754850000000005, 33.689, 33.62315, 33.557300000000005, 33.49145, 33.4256, 33.336200000000005, 33.2468, 33.1574, 33.068000000000005, 32.9786, 32.8892, 32.799800000000005, 32.7104, 32.621, 32.531600000000005, 32.4422, 32.3528, 32.3609, 32.369, 32.3771, 32.385200000000005, 32.3933, 32.4014, 32.4095, 32.4176, 32.425700000000006, 32.433800000000005, 32.441900000000004, 32.45, 32.5088, 32.5676, 32.626400000000004, 32.6852, 32.744, 32.802800000000005, 32.8616, 32.9204, 32.9792, 33.038, 33.0968, 33.1556, 33.26465, 33.3737, 33.482749999999996, 33.5918, 33.70085, 33.8099, 33.918949999999995, 34.028, 34.13705, 34.2461, 34.355149999999995, 34.4642, 34.49735, 34.530499999999996, 34.563649999999996, 34.5968, 34.62995, 34.6631, 34.69625, 34.7294, 34.762550000000005, 34.795700000000004, 34.82885, 34.862, 34.6304, 34.3988, 34.1672, 33.9356, 33.704, 33.4724, 33.2408, 33.0092, 32.7776, 32.546, 32.3144, 32.0828, 32.06555, 32.0483, 32.03105, 32.0138, 31.99655, 31.979300000000002, 31.96205, 31.9448, 31.92755, 31.9103, 31.893050000000002, 31.8758, 32.054300000000005, 32.232800000000005, 32.411300000000004, 32.589800000000004, 32.7683, 32.9468, 33.1253, 33.3038, 33.4823, 33.6608, 33.8393, 34.0178, 33.8447, 33.6716, 33.4985, 33.3254, 33.152300000000004, 32.9792, 32.8061, 32.633, 32.4599, 32.2868, 32.1137, 31.9406, 32.10425, 32.2679, 32.43155, 32.5952, 32.75885, 32.9225, 33.08615, 33.2498, 33.413450000000005, 33.5771, 33.740750000000006, 33.9044, 33.928250000000006, 33.9521, 33.975950000000005, 33.9998, 34.02365, 34.0475, 34.07135, 34.095200000000006, 34.11905, 34.142900000000004, 34.16675, 34.1906, 34.0916, 33.9926, 33.893600000000006, 33.7946, 33.6956, 33.5966, 33.497600000000006, 33.3986, 33.2996, 33.2006, 33.101600000000005, 33.0026, 32.98625, 32.9699, 32.95355, 32.9372, 32.92085, 32.9045, 32.888149999999996, 32.8718, 32.85545, 32.839099999999995, 32.82275, 32.8064, 32.77565, 32.744899999999994, 32.71415, 32.6834, 32.652649999999994, 32.6219, 32.59115, 32.560399999999994, 32.52965, 32.4989, 32.468149999999994, 32.4374]

New External Temp List:  2022-11-17 05:00:00    37.16960
2022-11-17 05:05:00    37.12130
2022-11-17 05:10:00    37.07300
2022-11-17 05:15:00    37.02470
2022-11-17 05:20:00    36.97640
                         ...
2022-11-18 03:40:00    32.56040
2022-11-18 03:45:00    32.52965
2022-11-18 03:50:00    32.49890
2022-11-18 03:55:00    32.46815
2022-11-18 04:00:00    32.43740
Length: 277, dtype: float64

                        cfm  sash  occ  internal temp  external temp
2022-11-17 05:00:00  224.13   1.2  1.0           72.2        37.1696
2022-11-17 05:05:00  224.13   1.2  1.0           72.4        37.1213
2022-11-17 05:10:00  224.13   1.2  1.0           72.4        37.0730
2022-11-17 05:15:00  225.10   1.2  1.0           72.1        37.0247
2022-11-17 05:20:00  225.10   1.2  1.0           71.8        36.9764
...                     ...   ...  ...            ...            ...
2022-11-19 04:35:00  224.13   1.2  0.0           70.3            NaN
2022-11-19 04:40:00  225.59   1.2  0.0           70.3            NaN
2022-11-19 04:45:00  227.06   1.2  0.0           70.2            NaN
2022-11-19 04:50:00  227.06   1.2  0.0           70.2            NaN
2022-11-19 04:55:00  221.20   1.2  0.0           70.2            NaN

[576 rows x 5 columns]

,cfm,sash,occ,internal temp,external temp,BTUh
2022-11-17 05:00:00,224.13,1.2,1.0,72.2,37.16960,8479.472636
2022-11-17 05:05:00,224.13,1.2,1.0,72.4,37.12130,8539.576233
2022-11-17 05:10:00,224.13,1.2,1.0,72.4,37.07300,8551.267751
2022-11-17 05:15:00,225.10,1.2,1.0,72.1,37.02470,8527.086032
2022-11-17 05:20:00,225.10,1.2,1.0,71.8,36.97640,8465.895749
...,...,...,...,...,...,...
2022-11-18 03:40:00,224.13,2.2,0.0,70.9,32.56040,9280.498912
2022-11-18 03:45:00,223.64,2.2,0.0,70.9,32.52965,9267.636680
2022-11-18 03:50:00,224.62,2.2,0.0,70.8,32.49890,9291.448529
2022-11-18 03:55:00,220.22,2.2,0.0,70.8,32.46815,9116.755208
2022-11-18 04:00:00,222.17,2.2,0.0,70.8,32.43740,9204.860349